= {project-name} Changelog
:project-name: malboxes
:uri-repo: https://github.com/GoSecure/malboxes
:uri-issue: {uri-repo}/issues/

This document provides a high-level view of the changes introduced in {project-name} by release.
For a detailed view of what has changed, refer to the {uri-repo}/commits/master[commit history] on GitHub.

== 0.3.1 *unreleased*

Enhancements::
* Added configuration parameters for keyboard locale and proxy settings
  ({uri-issue}72[#72], {uri-issue}78[#78])
* Chocolatey will force the proxy configuration if set ({uri-issue}74[#74])
* Custom provisioners can be defined in profiles configuration ({uri-issue}73[#73])

Bug fixes::
* Fixed `jinja2.exceptions.TemplateNotFound: snippets/builder_vsphere_windows.json` ({uri-issue}71[#71])
* Specified dependencies more precisely ({uri-issue}82[#82])


== 0.3.0

BlackHat USA Arsenal 2017 edition!

Enhancements::
* New templates: Windows 7 64-bit: win7_64_analyst ({uri-issue}42[#42])
* Experimental profiles features: a separate configuration from OS templates
  that enables to add new installed packages, files and registry changes ({uri-issue}51[#51])
* Support for trial versions of Windows 7 Enterprise x86 and x64
* Initial support for vSphere (ESXi / vCenter) on the back-end ({uri-issue}30[#30], {uri-issue}68[#68])
* Better out of the box support of Fedora, CentOS and RedHat as host ({uri-issue}53[#53])
* Use user cache directories for packer. This avoids caching in memory-backed locations to
  prevent unnecessary memory pressure during builds or free space issues on
  low RAM systems ({uri-issue}45[#45])
* Default timeout for WinRM is 60m (from 30m) to allow slower machines the time to go
  through Windows' install process
* Increased default disk size to 20GB
* Added a --force flag to overwrite pre-existing packer artifacts or vagrant boxes ({uri-issue}46[#46])
* debug: Passes -on-error=abort to packer to allow investigation of failures ({uri-issue}35[#35])
* Documentation improvements

Bug fixes::
* NetworkLocation changes for Windows 7 solves a class of 'Timeout waiting for WinRM' errors ({uri-issue}33[#33], {uri-issue}43[#43], {uri-issue}60[#60])
* Increased WinRM memory limit on Windows 7 solves errors installing .Net Framework 4.0 ({uri-issue}31[#31], {uri-issue}44[#44])
* More Windows 7 .Net Framework 4.0 fixes ({uri-issue}59[#59])

=== Release meta

* Released on: 2017-07-25
* Released by: @obilodeau
* Release beer: Sierra Nevada Hop Hunter IPA

Action: {uri-repo}/issues?q=is%3Aissue%20is%3Aclosed%20created%3A2017-02-16..2017-07-25[issues
created and resolved] |
{uri-repo}/compare/0.2.0...0.3.0[full diff]

=== Credits

Thanks to the following people who contributed to this release:

https://github.com/gleblanc1783[Gregory Leblanc],
https://github.com/xambroz[@xambroz],
https://github.com/malwarenights[@malwarenights],
https://github.com/svieg[Hugo Genesse] and
https://github.com/obilodeau[Olivier Bilodeau]


== 0.2.0

The _#RSAC gift_ release!

Enhancements::
  * Updated Windows 10 to Anniversary Edition ({uri-issue}21[#21])
  * `pip install` support and documentation ({uri-issue}5[#5])
  * Config: `ida_path` will upload IDA Remote Debugger and open appropriate ports ({uri-issue}8[#8])
  * Config: `tools_path` will upload all of this Path's content into `C:\Tools` ({uri-issue}8[#8])
  * Config: `username` and `password` support ({uri-issue}11[#11])
  * Config: Added `windows_defender`, `windows_updates`, `disk_size` and `choco_packages` options ({uri-issue}11[#11], {uri-issue}14[#14])
  * Provides `fiddler4` instead of `fiddler`
  * Provides `npcap` instead of `winpcap` which works with Windows 10 ({uri-issue}2[#2], {uri-issue}26[#26])
  * Added `--debug` and `--skip` command-line flags ({uri-issue}20[#20])
  * Added tests

Bug fixes::
  * Workaround for virtualbox 5.1.0 regression ({uri-issue}10[#10])
  * Packer binary is called `packer-io` on certain platforms ({uri-issue}3[#3])
  * Windows 10 x86 Automatic Installation issues ({uri-issue}4[#4])
  * Temporarily removed depwalker and regshot from choco packages ({uri-issue}16[#16])
  * VirtualBox Guest Additions: Support for the new certificate name ({uri-issue}24[#24])


=== Release meta

Released by @obilodeau on 2017-02-16.

// {uri-repo}/issues?q=milestone%3A1.0.0[issues resolved] |
{uri-repo}/releases/tag/0.2.0[git tag] |
{uri-repo}/compare/0.1.0...0.2.0[full diff]

=== Credits

Thanks to the following people who contributed to this release:

Olivier Bilodeau, Hugo Genesse


== 0.1.0

_NorthSec 2016 edition_

First proof of concept release of {project-name}.

We can build Windows 7 and Windows 10 virtual machines with useful malware
analysis tools pre-installed. Without a license key it will use the evaluation
version of Windows 10 which is automatically downloaded.

=== Release meta

Released by @obilodeau on 2016-05-17.

Announced live at the https://nsec.io/[NorthSec conference]. Here are
http://gosecure.github.io/presentations/2016-05-19_northsec/malboxes.html[the slides]
(http://gosecure.github.io/presentations/2016-05-19_northsec/OlivierBilodeau_HugoGenesse-Malboxes.pdf[PDF])
and here is
https://www.youtube.com/watch?v=rfmUcYGGrls&list=PLuUtcRxSUZUpg-z0MkDrFrwMiiFMVr1yI[the video].

=== Credits

Thanks to the following people who contributed to this release:

Olivier Bilodeau, Hugo Genesse
