= Malboxes
:toc: preamble
:toclevels: 2
:twob: https://twitter.com/obilodeau
:twhg: https://twitter.com/hugospns
// github stuff
ifdef::env-github[:status:]

// Travis Build Status
ifdef::status[]
.*Project health*
image:https://img.shields.io/travis/GoSecure/malboxes/master.svg[Build
Status (Travis CI), link=https://travis-ci.org/GoSecure/malboxes]
endif::[]


Vagrant box builder and config generator for malware analysis

https://github.com/gosecure/malboxes

== Requirements

* Python 3
* appdirs
* jinja2
* packer: https://www.packer.io/intro/getting-started/setup.html
* vagrant: https://www.vagrantup.com/downloads.html

== Installation

    sudo pip install git+https://github.com/GoSecure/malboxes.git@pip-packaging#egg=malboxes

== Usage

=== Box creation

Run:

    malboxes build <profile>

You can also list all supported profiles with:

    malboxes list

This will build a Vagrant box ready for malware investigation you can now
include it in a Vagrantfile afterwards.

For example:

    malboxes build win10_64_analyst

If you want to customize your configuration, look at the following location
for a `config.json` file:

* Linux/Unix: `~/.config/malboxes/`
* Mac OS X: `~/Library/Application Support/malboxes/`
* Win 7+: `C:\Users\<username>\AppData\Local\malboxes\malboxes\`


=== Per analysis instances

    malboxes spin win10_64_analyst <name>

This will create a `Vagrantfile` prepared to use for malware analysis. Move it
into the analysis folder of your choice and issue:

    vagrant up

From that folder to get the VM started. By default the local directory will be
shared in the VM. This can be changed by commenting the relevant part of the
`Vagrantfile`.

For example:

    malboxes spin win7_32_analyst 20160519.cryptolocker.xyz

// FIXME

=== Customization

You can modify (add, modify or delete) registry keys, directories and files like this:

Registry keys:

    malboxes registry <profile> <modtype> <key name> <value> <valuetype>

Example:

    malboxes registry win10_64_analyst add HKCU:\Software "Malboxes IsAwesome" String

Directories and files:

    malboxes directory <profile> <modtype> <dirpath>

Example:

    malboxes directory BadAPT57 delete C:\Windows\System32

You can add packages to install that are specific to the profile:

    malboxes package <profile> <package>

Example:

    malboxes package RansomwareThatINeedRevengeOn chrome

== More information

=== Applying DevOps Principles for Better Malware Analysis

A presentation about malboxes at
https://www.nsec.io/2016/01/applying-devops-principles-for-better-malware-analysis/[NorthSec]
by link:{twob}[Olivier Bilodeau] and link:{twhg}[Hugo Genesse]

* http://gosecure.github.io/presentations/2016-05-19_northsec/malboxes.html[Slides]
  (HTML, best)
* http://gosecure.github.io/presentations/2016-05-19_northsec/OlivierBilodeau_HugoGenesse-Malboxes.pdf[Slides]
  (PDF, degraded)
* Video (coming soon)

== License

Code is licensed under the GPLv3+, see `LICENSE` for details. Documentation
and presentation material is licensed under the Creative Commons
Attribution-ShareAlike 4.0, see `docs/LICENSE` for details.

== Credits

After I had the idea for an improved malware analyst workflow based on what
I've been using for development on Linux servers (Vagrant) I quickly Googled
if someone was already doing something in that regard.

I found the https://github.com/m-dwyer/packer-malware[packer-malware] repo on
github by Mark Andrew Dwyer. Malboxes was boostrapped thanks to his work which
helped me especially around the areas of `Autounattend.xml` files.
