= Development guide

== Install malboxes in development mode

From the project's git repository root directory, execute:

    sudo pip3 install -e . --no-deps


== Install a specific branch from github

Useful for testing pull requests. Replace `branchname` with the name of the
branch to test in the following command:

    pip3 install --upgrade git+https://github.com/GoSecure/malboxes.git@branchname#egg=malboxes


== Making a release

. Update the version in `malboxes/_version.py`
. Update the changelog
** linkify issues with vim's: `%s/#\(\d\d\)/{uri-issue}\1[#\1]/gc`
** Generate author list with:
+
    git log <commit>.. --format="%aN" --reverse | perl -e 'my %dedupe; while (<STDIN>) { print unless $dedupe{$_}++}' | sort

. Prepare release commit
** commit msg: Prepare %version% release
** release commit (--allow-empty) msg: Release %version%

. Tag the release commit
** Annotated Tag msg: Version %version%

. Push your changes (including the tag)
. Make a release on github (from changelog and copy from previous releases)

. Update version in `malboxes/_version.py` (+1 feature, append 'dev') and commit
** commit msg: Begin development on next release


== VirtualBox Management Commands

Useful commands:

    VBoxManage list vms

    VBoxManage showvminfo <vm>

    VBoxManage controlvm packer-virtualbox-iso-1488033522 poweroff

If that doesn't work, kill the VBoxHeadless process.

    VBoxManage unregistervm --delete <vm>


== How to View Errors from Scripts Called from Autounattend.xml

=== PowerShell

Add this to the end of PowerShell scripts:

    Write-Host "Press any key to continue ..."
    $x = $host.UI.RawUI.ReadKey("NoEcho,IncludeKeyUp")

This will pause scripts allowing you to see the output.

=== Command (cmd.exe)

    PAUSE

Will stop a batch script execution until a key is pressed.


== Other Packer Windows Initiatives

When facing problems, it is useful to check here for inspiration on how to fix
problems.

* https://github.com/joefitzgerald/packer-windows
* https://github.com/jedi4ever/veewee/tree/master/templates
* https://github.com/boxcutter/windows
